#!/bin/bash

set -euo pipefail

exec 3>&1
exec 1>&2
jq -M -S . < /dev/stdin > /tmp/input.json

if [ "$(jq -r '.version | has("pastebin")' < /tmp/input.json)" = 'true' ]; then
    pastebin=$(jq -r .version.pastebin < /tmp/input.json)
    package=$(jq -r .version.package < /tmp/input.json)
    version=$(jq -r .version.version < /tmp/input.json)
    cd "$1"
    case "$pastebin" in
        (https://paste.ubuntu.com/p/*)
            curl -fsSL "$pastebin" | grep -A 999999999 '<div class="paste"><pre>' | grep -B 999999999 "^</pre>" | sed -e "s/.*<pre><span><\/span>//" -e "s/^<\/pre>.*//" > autopkgtest.log
            ;;
        (https://paste.debian.net/*)
            curl -fsSL "$pastebin" | grep -A 999999999 '<div class="highlight"><pre>' | grep -B 999999999 "^</pre>" | sed -e "s/.*<pre><span><\/span>//" -e "s/^<\/pre>.*//" > autopkgtest.log
            ;;
    esac
else
    pastebin=
fi

if [ -z "$pastebin" ]; then
    echo "{}" >&3
else
    json='{"version":{"package":"'"$package"'","version":"'"$version"'","pastebin":"'$pastebin'"}}'
    jq -n "$json" >&3
fi
